<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/functions.php';
require_auth();

$pdo=db(); $id=(int)($_GET['id']??0); $dossier=fetch_dossier($pdo,$id); $metrics=delay_metrics($dossier);
$historyStmt=$pdo->prepare("SELECT h.*,u.name AS user_name FROM history h LEFT JOIN users u ON u.id=h.user_id WHERE h.entity_type='dossier' AND h.entity_id=? ORDER BY h.created_at DESC LIMIT 30"); $historyStmt->execute([$id]); $history=$historyStmt->fetchAll();
$pageTitle='Dossier #'.$id; $pageEyebrow=$dossier['nom'].' '.$dossier['prenom']; require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-actions"><a class="button button--secondary" href="<?= h(url('/pages/dossiers.php')) ?>">← Dossiers</a><div class="page-actions__group"><span class="<?= status_class($dossier['statut']) ?>"><?= h(status_label($dossier['statut'])) ?></span><span class="<?= priority_class($dossier['priority']) ?>"><?= h(priority_label($dossier['priority'])) ?></span><a class="button button--secondary" href="<?= h(url('/pages/dossier_form.php?id='.$id)) ?>">Modifier</a></div></div>

<section class="panel" style="margin-bottom:22px"><div class="panel__body"><div class="metric-strip">
 <div class="metric"><small>Date de départ</small><strong><?= date_fr($dossier['date_depart_delai']) ?></strong></div>
 <div class="metric"><small>Jours écoulés</small><strong><?= $metrics['active']?(int)$metrics['elapsed'].' jours':'—' ?></strong></div>
 <div class="metric"><small>Pause SAV</small><strong><?= (int)$metrics['pause_days'] ?> jour<?= $metrics['pause_days']>1?'s':'' ?></strong></div>
 <div class="metric"><small>Avant facturation</small><strong class="<?= ($metrics['raw_remaining']??1)<0?'overdue':'' ?>"><?= !$metrics['active']?'Non démarré':(($metrics['raw_remaining']??0)<0?'Retard de '.abs($metrics['raw_remaining']).' j':$metrics['remaining'].' jours') ?></strong></div>
</div></div></section>

<div class="grid-2">
<div style="display:grid;gap:22px">
 <section class="panel"><div class="panel__header"><h2>Échéances et facturation</h2></div><div class="panel__body"><dl class="detail-list">
   <div><dt>Client</dt><dd><a href="<?= h(url('/pages/client_view.php?id='.$dossier['client_id'])) ?>"><?= h($dossier['nom'].' '.$dossier['prenom']) ?></a></dd></div><div><dt>Appareil en stock</dt><dd><?= $dossier['appareil_en_stock']?'Oui':'Non' ?></dd></div>
   <div><dt>Date appareillage</dt><dd><?= date_fr($dossier['date_appareillage']) ?></dd></div><div><dt>Arrivée stock</dt><dd><?= date_fr($dossier['date_arrivee_stock']) ?></dd></div>
   <div><dt>Carte vitale prévue</dt><dd><?= date_fr($dossier['date_prevue_carte_vitale']) ?></dd></div><div><dt>Facturation prévue</dt><dd><?= date_fr($dossier['date_prevue_facturation']) ?></dd></div>
   <div><dt>Carte demandée</dt><dd><?= date_fr($dossier['date_carte_vitale_demandee']) ?></dd></div><div><dt>Carte récupérée</dt><dd><?= date_fr($dossier['date_carte_vitale_recuperee']) ?></dd></div>
   <div><dt>Total TTC</dt><dd><?= money_fr($dossier['total_ttc']) ?></dd></div><div><dt>Facturé</dt><dd><?= $dossier['facturation_status']==='oui'?'Oui, le '.date_fr($dossier['facturation_faite_le']):'Non' ?></dd></div>
 </dl></div></section>
 <section class="panel"><div class="panel__header"><h2>Données du dossier</h2></div><div class="panel__body"><dl class="detail-list"><div><dt>Ordonnance</dt><dd><?= h(ucfirst($dossier['ordo_status'])) ?> · <?= date_fr($dossier['date_ordo']) ?></dd></div><div><dt>Mutuelle / CSS</dt><dd><?= h($dossier['mutuelle_css']?:'—') ?></dd></div><div><dt>PEC</dt><dd><?= $dossier['pec_faite']?'Faite le '.date_fr($dossier['pec_faite_le']):'Non faite' ?></dd></div><div><dt>Facturer à partir de</dt><dd><?= date_fr($dossier['facturer_a_partir_de']) ?></dd></div></dl><h3>Commentaire</h3><p><?= nl2br(h($dossier['commentaire']?:'Aucun commentaire.')) ?></p><?php if($dossier['probleme_type']):?><div class="notice notice--error"><span><strong><?= h($dossier['probleme_type']) ?></strong><br><?= h($dossier['probleme_commentaire']) ?></span></div><?php endif;?><?php if($dossier['import_warning']):?><div class="notice notice--warning"><span><strong>Incohérence du fichier source</strong><br><?= h($dossier['import_warning']) ?></span></div><?php endif;?></div></section>
 <section class="panel"><div class="panel__header"><h2>Historique du dossier</h2></div><div class="panel__body timeline"><?php foreach($history as $event):?><div class="timeline__item"><strong><?= h(str_replace('_',' ',ucfirst($event['action']))) ?></strong><p><?= h($event['details']?:'Action enregistrée') ?></p><small><?= h($event['user_name']?:'Système') ?> · <?= date_fr($event['created_at']) ?> à <?= h(date('H:i',strtotime($event['created_at']))) ?></small></div><?php endforeach;?><?php if(!$history):?><div class="empty-state">Aucune action enregistrée.</div><?php endif;?></div></section>
</div>
<aside style="display:grid;align-content:start;gap:22px">
 <section class="panel"><div class="panel__header"><h2>Actions rapides</h2></div><div class="panel__body action-stack">
 <?php if($dossier['statut']==='attente_stock'):?><form method="post" action="<?= h(url('/actions/status_update.php')) ?>"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="start_delay"><?= csrf_field() ?><button class="button button--primary" type="submit">▶ Démarrer le délai 30 jours</button></form><?php endif;?>
 <?php if(!in_array($dossier['statut'],['facture','annule','attente_stock','sav'],true)):?><form method="post" action="<?= h(url('/actions/status_update.php')) ?>"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="waiting_stock"><?= csrf_field() ?><button class="button button--secondary" type="submit">□ Passer en attente stock</button></form><?php endif;?>
 <?php if($dossier['statut']==='carte_vitale_a_recuperer'):?><form method="post" action="<?= h(url('/actions/status_update.php')) ?>" data-confirm="La carte vitale est-elle bien récupérée ?"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="card_collected"><?= csrf_field() ?><button class="button button--warning" type="submit">✚ Carte vitale récupérée</button></form><?php endif;?>
 <?php if(!in_array($dossier['statut'],['facture','annule','sav'],true)):?><form method="post" action="<?= h(url('/actions/status_update.php')) ?>"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="to_invoice"><?= csrf_field() ?><button class="button button--warning" type="submit">€ Passer à facturer</button></form><?php endif;?>
 <?php if($dossier['statut']==='a_facturer'):?><form method="post" action="<?= h(url('/actions/status_update.php')) ?>" data-confirm="Confirmer que la facturation a été faite dans l’outil métier ?"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="invoice"><?= csrf_field() ?><button class="button button--success" type="submit">✓ Marquer facturé</button></form><?php endif;?>
 <?php if(!in_array($dossier['statut'],['facture','annule','sav'],true)):?><form method="post" action="<?= h(url('/actions/sav_start.php')) ?>"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><button class="button button--secondary" type="submit">↻ Mettre en SAV</button></form><?php endif;?>
 <?php if($dossier['statut']==='sav'):?><form method="post" action="<?= h(url('/actions/sav_end.php')) ?>"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><button class="button button--primary" type="submit">↻ Sortir du SAV</button></form><?php endif;?>
 </div></section>
 <?php if(!in_array($dossier['statut'],['facture','annule','problematique'],true)):?><section class="panel"><div class="panel__header"><h2>Signaler un problème</h2></div><form method="post" action="<?= h(url('/actions/problem_save.php')) ?>"><div class="panel__body form-grid"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><div class="field field--full"><label>Type</label><select name="probleme_type" required><option value="">Choisir…</option><?php foreach(problem_types() as $type):?><option value="<?= h($type) ?>"><?= h(ucfirst($type)) ?></option><?php endforeach;?></select></div><div class="field field--full"><label>Commentaire</label><textarea name="probleme_commentaire" required></textarea></div><div class="field field--full"><label>Action à faire</label><input name="probleme_action" placeholder="Relancer, vérifier, appeler…"></div></div><div class="panel__footer"><button class="button button--danger" type="submit">! Marquer problématique</button></div></form></section><?php endif;?>
 <?php if($dossier['statut']==='problematique'):?><section class="panel"><div class="panel__header"><h2>Résolution</h2></div><div class="panel__body"><p><?= h($dossier['probleme_action']?:'Vérifiez le dossier avant de résoudre le problème.') ?></p><form method="post" action="<?= h(url('/actions/problem_resolve.php')) ?>" data-confirm="Confirmer la résolution de ce problème ?"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><button class="button button--success" type="submit">✓ Résoudre le problème</button></form></div></section><?php endif;?>
 <section class="panel"><div class="panel__header"><h2>Ajouter un commentaire</h2></div><form method="post" action="<?= h(url('/actions/status_update.php')) ?>"><div class="panel__body"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="action" value="comment"><?= csrf_field() ?><div class="field"><label>Nouveau commentaire</label><textarea name="commentaire" required placeholder="Ce commentaire sera ajouté au dossier…"></textarea></div></div><div class="panel__footer"><button class="button button--secondary" type="submit">Ajouter</button></div></form></section>
</aside></div>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
