<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/functions.php';require_auth();
$preview=$_SESSION['csv_import']??null;$imports=db()->query('SELECT i.*,u.name AS user_name FROM imports i LEFT JOIN users u ON u.id=i.created_by ORDER BY i.created_at DESC LIMIT 10')->fetchAll();
$targets=[
 'nom'=>'NOM *','prenom'=>'Prénom *','ordo'=>'ORDO (Oui/Non)','date_ordo'=>'DATE ORDO','mutuelle'=>'MUTUELLE / CSS','date_appareillage'=>'DATE APPAREILLAGE','total'=>'TOTAL (TTC)','pec_faite'=>'PEC Faite','pec_date'=>'PEC Faite le','facturer_date'=>'FACTURER À PARTIR DE','facturation'=>'FACTURATION (Oui/Non)','facturation_date'=>'Facturation Faite le','commentaire'=>'COMMENTAIRE'
];
$pageTitle='Import Excel / CSV';$pageEyebrow='Reprise du suivi existant';require dirname(__DIR__).'/includes/header.php';
?>
<div class="notice notice--info"><span><strong>Import V1 :</strong> exportez votre fichier Excel en CSV UTF-8. Les dates incomplètes et erreurs de formule sont signalées sans bloquer les autres lignes.</span></div>
<?php if(!$preview):?>
<div class="grid-2"><section class="panel"><div class="panel__header"><h2>1. Choisir un fichier CSV</h2></div><form method="post" enctype="multipart/form-data" action="<?= h(url('/actions/import_excel_action.php')) ?>"><div class="panel__body"><input type="hidden" name="stage" value="preview"><?= csrf_field() ?><label class="upload-zone"><strong>Déposer ou sélectionner le fichier</strong><span class="muted" id="file-name">CSV, 5 Mo maximum</span><input type="file" name="csv_file" accept=".csv,text/csv" required data-file-label="#file-name"></label></div><div class="panel__footer"><button class="button button--primary" type="submit">Prévisualiser et mapper</button></div></form></section><aside class="panel"><div class="panel__header"><h2>Ce que fait l’import</h2></div><div class="panel__body kpi-list"><div class="kpi-row"><span>Doublon client</span><strong>Nom + prénom</strong></div><div class="kpi-row"><span>Une ligne</span><strong>Un dossier</strong></div><div class="kpi-row"><span>Dates invalides</span><strong>Signalées</strong></div><div class="kpi-row"><span>Commentaires à risque</span><strong>Alerte</strong></div></div></aside></div>
<?php else:?>
<form method="post" action="<?= h(url('/actions/import_excel_action.php')) ?>"><input type="hidden" name="stage" value="commit"><?= csrf_field() ?><section class="panel" style="margin-bottom:22px"><div class="panel__header"><div><h2>2. Mapper les colonnes</h2><small class="muted"><?= h($preview['file_name']) ?> · <?= count($preview['rows']) ?> lignes détectées</small></div><a class="button button--secondary button--small" href="<?= h(url('/actions/import_excel_action.php?cancel=1')) ?>">Annuler</a></div><div class="panel__body mapping-grid"><?php foreach($targets as $key=>$label):?><div class="mapping-item"><label><?= h($label) ?></label><select name="map[<?= h($key) ?>]"><option value="">Ne pas importer</option><?php foreach($preview['headers'] as $idx=>$header):?><option value="<?= (int)$idx ?>" <?= isset($preview['auto_map'][$key])&&$preview['auto_map'][$key]===$idx?'selected':'' ?>><?= h($header?:'Colonne '.($idx+1)) ?></option><?php endforeach;?></select></div><?php endforeach;?></div><div class="panel__footer page-actions"><span class="muted">Vérifiez surtout NOM et Prénom.</span><button class="button button--primary" type="submit">Valider et importer</button></div></section></form>
<section class="panel"><div class="panel__header"><h2>Aperçu des 8 premières lignes</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><?php foreach($preview['headers'] as $head):?><th><?= h($head) ?></th><?php endforeach;?></tr></thead><tbody><?php foreach(array_slice($preview['rows'],0,8) as $row):?><tr><?php foreach($preview['headers'] as $i=>$head):?><td><?= h(mb_strimwidth($row[$i]??'',0,45,'…')) ?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<?php if($imports):?><section class="panel" style="margin-top:22px"><div class="panel__header"><h2>Derniers imports</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Fichier</th><th>Lignes</th><th>Réussies</th><th>Alertes / erreurs</th><th>Par</th></tr></thead><tbody><?php foreach($imports as $i):?><tr><td><?= date_fr($i['created_at']) ?></td><td><?= h($i['file_name']) ?></td><td><?= (int)$i['total_rows'] ?></td><td><span class="badge badge--facture"><?= (int)$i['success_rows'] ?></span></td><td><span class="badge <?= $i['error_rows']?'badge--problematique':'badge--facture' ?>"><?= (int)$i['error_rows'] ?></span></td><td><?= h($i['user_name']?:'—') ?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
