<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/functions.php';
require_auth();
$preview = $_SESSION['cosium_preview'] ?? null;
$pageTitle = 'Import PDF Cosium';
$pageEyebrow = 'Création assistée de fiche client';
require dirname(__DIR__) . '/includes/header.php';
?>
<div class="notice notice--info"><span>Le PDF est lu sur ce PC. Aucun document ni donnée patient n’est envoyé sur Internet, et le fichier temporaire est supprimé après lecture.</span></div>
<?php if (!$preview): ?>
<div class="grid-2"><section class="panel"><div class="panel__header"><h2>Déposer une fiche Cosium</h2></div><form method="post" enctype="multipart/form-data" action="<?= h(url('/actions/cosium_pdf_action.php')) ?>"><div class="panel__body"><input type="hidden" name="stage" value="preview"><?= csrf_field() ?><label class="upload-zone"><strong>Choisir le PDF Cosium</strong><span class="muted" id="cosium-file-name">PDF, 10 Mo maximum</span><input type="file" name="cosium_pdf" accept="application/pdf,.pdf" required data-file-label="#cosium-file-name"></label></div><div class="panel__footer"><button class="button button--primary" type="submit">Lire et préremplir la fiche</button></div></form></section><aside class="panel"><div class="panel__header"><h2>Lecture automatique</h2></div><div class="panel__body kpi-list"><div class="kpi-row"><span>PDF avec texte</span><strong>Lecture directe</strong></div><div class="kpi-row"><span>PDF scanné</span><strong>OCR local</strong></div><div class="kpi-row"><span>Données détectées</span><strong>À valider</strong></div><div class="kpi-row"><span>Dossiers Cosium</span><strong>Conservés</strong></div></div></aside></div>
<?php else: $data=$preview['parsed']; ?>
<form method="post" action="<?= h(url('/actions/cosium_pdf_action.php')) ?>"><input type="hidden" name="stage" value="commit"><?= csrf_field() ?><section class="panel" style="margin-bottom:22px"><div class="panel__header"><div><h2>Vérifier les informations lues</h2><small class="muted"><?= h($preview['file_name']) ?> · <?= h($preview['method']) ?></small></div><a class="button button--secondary button--small" href="<?= h(url('/actions/cosium_pdf_action.php?cancel=1')) ?>">Annuler</a></div><div class="panel__body form-grid form-grid--3">
<div class="field"><label>Nom *</label><input name="nom" required value="<?= h($data['nom']) ?>"></div><div class="field"><label>Prénom *</label><input name="prenom" required value="<?= h($data['prenom']) ?>"></div><div class="field"><label>Numéro Cosium</label><input name="cosium_numero" value="<?= h($data['cosium_numero']) ?>"></div>
<div class="field"><label>Date de naissance</label><input type="date" name="date_naissance" value="<?= h($data['date_naissance']) ?>"></div><div class="field"><label>Fiche créée dans Cosium le</label><input type="date" name="date_creation_cosium" value="<?= h($data['date_creation_cosium']) ?>"></div><div class="field"><label>Téléphone</label><input name="telephone" value="<?= h($data['telephone']) ?>"></div>
<div class="field"><label>E-mail</label><input type="email" name="email" value="<?= h($data['email']) ?>"></div><div class="field field--full"><label>Adresse</label><textarea name="adresse"><?= h($data['adresse']) ?></textarea></div><div class="field"><label>Caisse de sécurité sociale</label><input name="caisse_secu" value="<?= h($data['caisse_secu']) ?>"></div>
<div class="field"><label>Numéro de sécurité sociale</label><input name="numero_securite_sociale" value="<?= h($data['numero_securite_sociale']) ?>" autocomplete="off"></div><div class="field"><label>Complémentaire</label><input name="complementaire" value="<?= h($data['complementaire']) ?>"></div><div class="field"><label>Assuré</label><input name="assure_nom" value="<?= h($data['assure_nom']) ?>"></div><div class="field field--full"><label>Notes</label><textarea name="notes"><?= h($data['notes']) ?></textarea></div>
</div></section>
<section class="panel"><div class="panel__header"><h2>Dossiers détectés dans Cosium</h2><span class="badge badge--dossier-en-cours"><?= count($data['dossiers']) ?></span></div><div class="panel__body"><?php if($data['dossiers']):?><div class="table-wrap"><table class="data-table"><thead><tr><th>Type</th><th>Date</th><th>Détails lus</th></tr></thead><tbody><?php foreach($data['dossiers'] as $d):?><tr><td><span class="badge badge--dossier-en-cours"><?= h($d['type']) ?></span></td><td><?= date_fr($d['date']) ?></td><td><?= h($d['details']?:'—') ?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="empty-state">Aucun dossier daté n’a été détecté dans ce PDF.</div><?php endif;?>
<?php if(array_filter($data['dossiers'],fn($d)=>str_contains($d['type'],'AUDITION'))):?><label style="display:flex;gap:8px;margin-top:14px"><input type="checkbox" name="create_audition_dossiers" value="1" checked> Créer aussi les dossiers audition dans Raja en attente stock.</label><?php endif;?>
<?php if($preview['existing_client']):?><div class="notice notice--warning" style="margin-top:16px"><span>Un client Raja correspondant existe déjà. Les informations Cosium seront rattachées à sa fiche.</span></div><input type="hidden" name="existing_client_id" value="<?= (int)$preview['existing_client']['id'] ?>"><?php endif;?></div><div class="panel__footer page-actions"><span class="muted">Relisez les champs issus de l’OCR avant validation.</span><button class="button button--primary" type="submit"><?= $preview['existing_client']?'Mettre à jour le client':'Créer la fiche client' ?></button></div></section></form>
<?php endif; ?>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
