<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/functions.php';require_roles(['admin']);$pdo=db();
$editId=(int)($_GET['id']??0);$edit=['id'=>0,'name'=>'','email'=>'','role'=>'employe','is_active'=>1];if($editId){$s=$pdo->prepare('SELECT id,name,email,role,is_active FROM users WHERE id=?');$s->execute([$editId]);$edit=$s->fetch()?:$edit;}
$users=$pdo->query('SELECT id,name,email,role,is_active,last_login_at,created_at FROM users ORDER BY is_active DESC,name')->fetchAll();
$pageTitle='Utilisateurs';$pageEyebrow='Accès et rôles';require dirname(__DIR__).'/includes/header.php';
?>
<div class="grid-2"><section class="panel"><div class="panel__header"><h2>Comptes Raja</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Utilisateur</th><th>Rôle</th><th>État</th><th>Dernière connexion</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td class="cell-main"><strong><?= h($u['name']) ?></strong><small><?= h($u['email']) ?></small></td><td><?= h(ucfirst($u['role'])) ?></td><td><span class="badge <?= $u['is_active']?'badge--facture':'badge--annule' ?>"><?= $u['is_active']?'Actif':'Désactivé' ?></span></td><td><?= date_fr($u['last_login_at']) ?></td><td><a class="button button--secondary button--small" href="<?= h(url('/pages/users.php?id='.$u['id'])) ?>">Modifier</a></td></tr><?php endforeach;?></tbody></table></div></section>
<aside class="panel"><div class="panel__header"><h2><?= $edit['id']?'Modifier le compte':'Nouveau compte' ?></h2></div><form method="post" action="<?= h(url('/actions/user_save.php')) ?>"><div class="panel__body form-grid"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><?= csrf_field() ?><div class="field field--full"><label>Nom *</label><input name="name" required maxlength="120" value="<?= h($edit['name']) ?>"></div><div class="field field--full"><label>E-mail *</label><input type="email" name="email" required maxlength="190" value="<?= h($edit['email']) ?>"></div><div class="field"><label>Rôle</label><select name="role"><?php foreach(['employe'=>'Employé','patron'=>'Patron','admin'=>'Admin'] as $k=>$v):?><option value="<?= $k ?>" <?= $edit['role']===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select></div><div class="field"><label>État</label><select name="is_active"><option value="1" <?= $edit['is_active']?'selected':'' ?>>Actif</option><option value="0" <?= !$edit['is_active']?'selected':'' ?>>Désactivé</option></select></div><div class="field field--full"><label>Mot de passe <?= $edit['id']?'(laisser vide pour conserver)':'*' ?></label><input type="password" name="password" <?= $edit['id']?'':'required' ?> minlength="10" autocomplete="new-password"><small>10 caractères minimum.</small></div></div><div class="panel__footer"><button class="button button--primary" type="submit">Enregistrer</button></div></form></aside></div>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
